---
title: The shoes were still there
aliases:
- /shoes-in-my-soul.html
date: 2024-03-31 18:11
categories:
- organizations
---

Trinh Nhoc is 90 years old.  He rather sweetly describes himself (in French) as
a "un bon cordonnier vietnamien" — a good shoemaker from Vietnam.

> In 1970, the coup happened in Cambodia. That first night, I remember
Cambodian soldiers knocking on the door of my shop.
>
> They knocked for five minutes.  That night they arrested many of my friends
> — and after that, they all died.  They all died.
>
> And that's why I had to go back to Vietnam.  It was very difficult for me,
because I left everything in Cambodia.  The leather, the materials, the
customers, the machines.
>
> I thought my career was over.  But deep in my heart, the shoes were still
there.

From Netflix "Stories of a generation — with Pope Francis": "Episode 4: Work",
starting at 15:23.

At around 30 minutes, we see a customer arriving to collect the shoes he has
ordered.  The customer is clearly pleased.  The camera catches Mr Ngoc's face
as he looks past the cameraman with such a pride that it should better be said
as joy.
