---
title: On John
aliases:
- /on-john.html
date: 2026-08-16 14:27
categories:
- NT criticism
---

For the last month or so, I have been reading (a lot), and writing (a little) about early testimony on the authors of the Gospels, and particularly, the author of the Gospel of John.

A friend — most reasonably — asked why.  This is an answer.

For a long time, I have been — what is the word? — devoted to John's Gospel,
and John's letters.

There is something mesmerizing about them.  I see it — feel it — at once with
the start of John's Gospel:

> In the beginning was the Word,
>
> and the Word was with God,
>
> and the Word was God.
>
> He was with God in the beginning.
>
> Through him all things were made;
>
> without him nothing was made that has been made.
>
> In him was life,
>
> and that life was the light of all mankind.
>
> The light shines in the darkness,
>
> and the darkness has not overcome it.

There is architecture there.  You have to look up, in awe.

It is as if you have entered a room, to find an old man, half in prayer, half
teaching — talking to himself, but speaking into history.  You can almost
hear him saying, perhaps muttering ([interlinear English
/ Greek](https://biblehub.com/interlinear/john/1.htm)):

> En archē ēn ho logos,
>
> kai ho logos ēn pros ton theon,
>
> kai theos ēn ho logos.

And you can also feel — this man loves — worships — his friend, who spoke so
fully, who lived as he did.  A few verses on at the start of the Gospel:

> The Word became flesh
>
> and made his dwelling among us.
>
> We have seen his glory,
>
> the glory of the one and only Son,
>
> who came from the Father,
>
> full of grace and truth.

The letters read like the same old man — [the
elder](https://www.biblegateway.com/passage/?search=2%20John%201&version=PHILLIPS)
— as he talks, astonished, about what he has seen:

> We are writing to you about something which has always existed yet which we
ourselves actually saw and heard: something which we had an opportunity to
observe closely and even to hold in our hands, and yet, as we know now, was
something of the very Word of life himself! For it was life which appeared
before us: we saw it, we are eye-witnesses of it, and are now writing to you
about it. It was the very life of all ages, the life that has always existed
with the Father, which actually became visible in person to us mortal men. We
repeat, we really saw and heard what we are now writing to you about.

That's how I read it.  It's almost like music, like a long, beautiful song,
full of structure and detail, but yet, nothing could be different; once it is
written, we see it must be as it is.

That's how I read it, but then I read many commentators, and historians, and
they say — well, he can't be an eye-witness, why does Jesus speak in this way,
it doesn't sound like the Jesus of the synoptic Gospels (Matthew, Mark, Luke),
how did a fisherman learn to write Greek like that, where do they come from,
all these long speeches by Jesus, surely this "John" did not remember them?

And for many of those commentators, the answer is — it's just some person, we
know not who, who made it up — it's a fantasy — a fake; it's a story, maybe
a lovely story, but nothing but.

I was mystified by that conclusion.  The Gospel just doesn't read that way — in
part because it is just so astonishing, unlike anything else in the world
before and during and after the New Testament.  What kind of mind was this,
that could make that up?   And how, in God's name, did the church and every
scholar since that time, lose track of this writer, perhaps the most gifted of
all antiquity?   Or, it is really true, as some have said, that there was some
set of people, who all learned to talk this way, and wrote in John's name
— although, strikingly, he is not named in the Gospel or the letters.

I hadn't read anything like the Gospel or letters of John, but perhaps there
were others who wrote that way.  So I went reading, and no, there are no others
who wrote that way.   I've read quite a lot of early church writing now — some
of it is boring, some it is silly and credulous, some of it is moving and
impressive, but there is nothing anything like the Gospel or the letters.

And I began to wonder, as you can see in some of my posts: is this — the
historical study of early church writing — just another field that has fallen
into irrelevance with capture by the need for cleverness, for ostentatious
learning, for novelty — for [fascinating
speculations]({filename:fascinating_speculations.pdc)?  Has that study wandered
into some faint and fantasy realm where they just cannot see — as Lightfoot
puts it above — the "historical position in all its bearings".

Now I read, and read, and forget, trying to keep track of what has happened,
what has been said, analysing arguments to find those that are foolish,
speculative — and those that are sound, and must be answered.

Of course it's hard.  As Lightfoot says, many, perhaps not most of the people
writing about these matters, do have good arguments, that must be answered.
But many, perhaps most, perhaps the same people, make assertions that are far
too strong, or must be wrong.   It is rocky, uneven ground, and full of houses
set up, taken down, in ruins, or ruined and rebuilt.

In this strange landscape, I wonder — who did write John?  The writer writes
very simple Greek, as you can feel in the English — with simpler syntax and
a smaller vocabulary than the other Gospel writers.   He knows many things
about the world of the Gospel that an eye-witness would know, and a forger
would not.   Maybe it was John, the brother of James, the fisherman.  Maybe it
was someone else.   Now would we know — without falling into safety or
speculation?

It's another one of those big problems — how would I know if I was wrong?
— especially here, where I have strong engagements.

That is why.
