---
title: Irenaeus and the author of John's Gospel
aliases:
- /irenaeus-john.html
date: 2026-08-01 15:00
categories:
- NT criticism
bibliography:
- ../../bible.bib
section-cites:
  id-prefix: sec
  auto-id-headings: false
  works:
    ah:
      label: AH
      names:
      - preface
      scheme: cite
      target: /posts/irenaeus-excerpts
    if:
      label: IF
      scheme: number
      target: /posts/irenaeus-excerpts
---

## The central question

Church tradition has the apostle John as the author of the Gospel according to
John, and the three letters of John (1 John, 2 John, 3 John).

By "the apostle John" I mean John, son of Zebedee, brother of James, one of the
twelve named apostles in the Gospels.  At the beginning of e.g. Mark (Mark
1:16-20), he is a fisherman, working in a business with his brother and father:

> Now walking beside the sea of Galilee, he saw Simon and Andrew his brother,
sons of Simon, casting a net in the sea; for they were fishermen. And Jesus
said to them, Come-here after me and I will make you to become fishermen of
men. And immediately they left their nets and followed him. And he advanced
a few feet from there and saw James and John his brother, the sons of Zebedee,
and they were in the ship mending the nets. And immediately he called them, and
they left their father Zebedee with the hired-hands in the ship and went after
him. (Modern Literal Version - MLV)[^mlv]

[^mlv]: Translation from the [Modern Literal Version — Aug
2026](https://modernliteralversion.org/mlv/MLVBL.pdf)

For reasons that will soon become clear, I will call this person "John son of
Zebedee" or JsZ for short.

For the moment, I'll assume that there is a single primary author of John's
Gospel.  Let's say we don't know who that author is.  So we'll call this person
the "Author of John's Gospel" or AJG for short.

For reasons I won't detail here, but discussed in @lightfoot1904biblical_essays
(chapter I, p3) and most famously described in @dodd1963historical, there is
internal evidence that AJG knew geographical and historical details of
first-century Palestine and Jerusalem and Judaism, that make it tempting to
assume that AJG was an eye-witness.  JsZ would have been such an eye-witness.
But was he the author of John?

The Gospel itself indicates that it was written by "the disciple whom Jesus
loved", otherwise written as "the beloved disciple". From John 21:21-22,24:

> But Peter turned again and sees the disciple whom Jesus loved following; who
also leaned-back upon his chest at the supper and who had said, Lord, who is he
who is giving you up? ... This is the disciple who is testifying concerning
these things and wrote these things and we know that his testimony is true.

For various reasons, it seems likely that we are to understand it was this
disciple who was the "other disciple" that went with Peter to the house of the
High Priest while Jesus was being tried (John 18:15-16):

> Now Simon Peter was following Jesus and the other disciple. Now that disciple
was known to the high-priest and entered in together-with Jesus into the
courtyard of the high-priest; but Peter stood outside before the door.
Therefore, the other disciple, who was known to the high-priest, went forth and
spoke to the doorkeeper and led in Peter. (MLV)

It's possible, but hard, to see how a fisherman, even someone who worked in
a business with hired hands, would have been "known to the high-priest".

One response to this and other difficulties, is to suggest that John, the
beloved disciple, was a disciple named John, other than JsZ.  Martin Hengel
made this proposal in @hengel1989johannine, followed by @bauckham1993papias and
others.

However, there is a hard test for this hypothesis, in the form of [Irenaeus of
Lyons](https://en.wikipedia.org/wiki/Irenaeus).  He wrote several works in the
late second century, listed below, that cite John and refer to the authorship
of the Gospel and letters.  He would have had good reason to know who had
written the Gospel and letters, because he had been a disciple of
[Polycarp](https://en.wikipedia.org/wiki/Polycarp) (c69 AD - c155 AD), who had
in turn been taught by a John who had seen Jesus.  Irenaeus writes, in
@if-ii (letter to Florinus):

> I can even describe the place where the blessed Polycarp used to sit and
discourse — his going out, too, and his coming in — his general mode of life
and personal appearance, together with the discourses which he delivered to the
people; also how he would speak of his familiar intercourse with John, and with
the rest of those who had seen the Lord; and how he would call their words to
remembrance.

As we will see, it must be this John that Irenaeus believes to be AJG.

So, there is a strong eye-witness tradition linking AJG to Irenaeus, through
Polycarp, and perhaps through
[Pothinus](https://en.wikipedia.org/wiki/Saint_Pothinus), Irenaeus' predecessor
as Bishop of Lyons, who may also have been a disciple of Polycarp.

The test for the Hengel / Bauckham hypothesis, is whether Irenaeus' substantial
extant writings can reasonably be read on the understanding that Irenaeus knew
that AJG was not JsZ, but another disciple of Jesus, also called John.

That is the theme for the rest of the page, starting with some discussion and
summary, and ending with all evidence I could bring to bear from Irenaeus'
writing.

As [J\ B\. Lightfoot](../fascinating-speculations/) points out, it is
worth reading Irenaeus directly on his testimony to the four Gospels, and
especially John:

> If any reader is really in earnest on [the four-Gospel Canon], I will ask him
to read Irenaeus and judge for himself. He will find many things for which
perhaps he is not prepared, and which will jar with his preconceived ideas; but
on the one point at issue I have no fear that I shall be accused of
exaggeration. Indeed it is impossible to convey in a few paragraphs the whole
force of an impression which is deepened by each successive page of a long and
elaborate work. [@lightfoot1889supernatural, p271]

To anticipate, it does seem to me that Irenaeus' writing is compatible with AJG
as JsZ, or with AJG being another of Jesus' disciples, also called John. It's
striking that AJG in Irenaeus is very specifically and often called "the
disciple of the Lord", which seems to have been a familiar title of AJG, and no
other disciple.  Perhaps this suggests "the disciple whom Jesus loved" of the
Gospel text.

See "Summary of results" below for more detail.

## Irenaeus and his texts

Irenaeus' life and writing are summarized in:

* [Wikipedia on Irenaeus](https://en.wikipedia.org/wiki/Irenaeus)
* [Britannica on Irenaeus](https://www.britannica.com/biography/Irenaeus)
* [Development of the NT Canon:
  Irenaeus](http://www.ntcanon.org/Irenaeus.shtml)

His known works are: (see Britannica):

* Against heresies (AH)
* Demonstration of the Apostolic Preaching (DAP)
* Various fragments.

Eusebius of Caesarea quotes from, and refers to Irenaeus' work in his
[Ecclesiastical
History](https://en.wikipedia.org/wiki/Ecclesiastical_History_(Eusebius)) (EH)
— [316-326 AD](https://www.bartehrman.com/eusebius-church-history/) (also see
J. B. Lightfoot's biography of Eusebius [-@lightfoot1880eusebius]).

## Use of John and "apostle" in Irenaeus' writing

Most of the quotes here are from Irenaeus' five books of [Against
Heresies](https://en.wikipedia.org/wiki/Against_Heresies) — abbreviated AH, but
I also cover Irenaeus' other known work, as you'll see below.

The quotes below record all mentions of "John" and "apostle" in Irenaeus, to
document who Irenaeus thinks John is, and how Irenaeus uses the term "apostle",
and whether, and in what sense, Irenaeus considered John to be an apostle.

## Sources

@anf01 has the full text in English translation. @harvey1857sancti_irenaei_2 is
an edition of the Latin text that is our main source for AH.  I refer to the AH
text below by book number, chapter number (in Roman numerals) and section number
— e.g AH 4, XXXV:2.  Follow the link to see the quote in context, along wit the
page number in @ah01, and the corresponding link to the [Bibliothek der
Kirchenväter site](https://bkv.unifr.ch) giving Roberts' text as clean web
pages.

As a side-note, we aren't likely to have any difficulty using the English
translation for "apostle", as Greek αποστολος is Latin *apostolus*.

## Summary of results

### John the disciple of the Lord

When referring to John the author, Irenaeus very often uses the set phrase
"John, the disciple of the Lord" (14 times of 49 total uses of "John" other
than John the Baptist).  There are two places where he indicates John by
"disciple of the lord", or "His disciple", without naming him, although John
is clear from the context: @ah-3-xi-3, @ah-3-xvi-8. He does not use the phrase "disciple of the Lord" of
any other person, though he several times refers in general to the "disciples
of the Lord" or "His disciples" in @ah-2-ii-5; @ah-3-xii-4-5 (twice); @ah-3-xii-14; @ah-3-xvi-5; @ah-5-xxxiv-3.

So "disciple of [the,our] Lord", or "the Lord's disciple" in Irenaeus *always*
means John the author of the Gospel or the letters, or the Apocalypse.

This is similar to the phrasing of Papias, quoted by Eusebius in
@mcgiffert1890eusebius (EH III. 39, p289). From @lightfoot1891fathers, p529,
(quoting Eusebius, quoting Papias):

> And again, any occasion when a person came (in my way) who had been
a follower of the Elders, I would inquire about the discourses of the
elders — what was said by Andrew, or by Peter, or by Philip, or by Thomas or
James, or by John or Matthew or any other of the Lord’s disciples, and what
Aristion and the Elder John, the disciples of the Lord, say.

John's Gospel gives its own primary author as "the beloved disciple" (John
21:24), who is not otherwise explicitly named or identified.

The author of the second and third letters of John introduces himself only as
"The elder" (2 John 1:1, 3 John 1:1).

Revelation (the Apocalypse) names its source as "[Jesus Christ's] servant
John" (Revelation 1:1)

### Irenaeus' apostles

Irenaeus only ever uses "the Apostle N" or "N the Apostle" for: Paul (17
times); Matthew (once of 17 mentions of "Matthew") and Peter (once for 48
mentions of "Peter").  He never uses "the Apostle John" or "John the Apostle".

For Irenaeus, the most representative apostles are Peter and Paul — he
criticizes the heretics for claiming to be "superior to his disciples, such as
Peter and Paul, and the rest of the apostles" @ah-1-xxv-2,
and contrasts the heretics' teaching with that of the apostles with "Therefore
let them not any longer assert that Peter and Paul and the other apostles
proclaimed the truth ..." @ah-4-xxxv-2.

In his letters, Paul specifically and often identifies himself as an "apostle of Christ Jesus" (e.g. Romans 1:1, 1 and 2 Corinthians 1), but did not claim to have met Jesus in person.

When referring to apostles, Irenaeus sometimes means:

1. The 12 named apostles; I've labeled these references as "12" below.
1. Paul
1. The source of definitive teaching from and about Jesus. I've labeled these
   references as "SA".

The question at hand is whether Irenaeus, when citing the apostles as general
authority (SA), restricted the apostles to the 12 plus Paul.

As background, it is clear from the quotes below that:

1. Irenaeus identifies the author of John's Gospel as John, the disciple of
   the Lord: "... John, the disciple of the Lord, who also had leaned upon His
   breast, did himself publish a Gospel during his residence at Ephesus in
   Asia." @ah-3-i-1.  Also: "And to these things does John
   also, the disciple of the Lord, bear witness, when he speaks thus in the
   Gospel: “In the beginning was the Word, and the Word was with God, and the
   Word was God. ..." @ah-5-xviii-2.
1. The same John, disciple of the Lord, is the author of the Apocalypse: "And
   if any one will devote a close attention to those things ... which John the
   disciple of the Lord saw in the Apocalypse," ... @ah-4-xxx-4.
1. The same John is the author of letters 1 John and 2 John. @ah-1-xvi-3 has
   "John, the disciple of the Lord ... says ..." followed by a quote from
   2 John. In @ah-3-xvi-8: "His disciple, in his Epistle already mentioned,"
   (quoting 2 John), and later: "Wherefore he again exclaims in his Epistle,"
   (quoting 1 John).
1. Irenaeus considered John the disciple of the Lord to be an apostle: "[the
   heretics assert that John] has, by thus speaking, referred to the primary
   Ogdoad,[^ogdoad] in which there was as yet no Jesus, and no Christ, the
   teacher of John. But that the apostle did not speak concerning their
   conjunctions, but concerning our Lord Jesus Christ, whom he also
   acknowledges as the Word of God, he himself has made evident. For, summing
   up his statements respecting the Word previously mentioned by him, he
   further declares, "And the Word was made flesh, and dwelt among us."
   (@ah-1-ix-2-3).

[^ogdoad]: See [Wikipedia — Ogdoad
  (Gnosticism)](https://en.wikipedia.org/wiki/Ogdoad_(Gnosticism))

The question though, is whether Irenaeus is asserting that John — the disciple
of the Lord — was also one of the 12.  Could he, instead, have been referring
to some other John, who was an apostle in the sense of being one of Jesus'
disciples, and therefore, a source of reliable testimony?

Irenaeus does use this second, more general interpretation of apostle, when he
argues that John the Baptist could be considered an apostle, because "he
actually saw [[Jesus]] when he came, and pointed him out":

> Wherefore the Lord said that He deemed [[John the Baptist]] "more than
a prophet." For all the other prophets preached the advent of the paternal
Light, and desired to be worthy of seeing Him whom they preached; but John did
both announce [the advent] beforehand, in a like manner as did the others, and
actually saw Him when He came, and pointed Him out, and persuaded many to
believe on Him, so that he did himself hold the place of both prophet and
apostle. For this is to be more than a prophet, because, "first apostles,
secondarily prophets;" ... @ah-3-xi-4.

There is another piece of suggestive evidence that Irenaeus allows other
disciples of Jesus to be apostles.  He writes: "For that Judas the traitor is
the twelfth in order, is agreed upon by all, there being twelve apostles
mentioned by name in the Gospel." @ah-2-xx-4; "mentioned by name" weakly
implies there may be other apostles not mentioned by name.

## Use of "apostle" in early church writing

What did other early church writers mean by the term "apostle"?

First note that Acts 14:14 (MLV) describes
[Barnabas](https://en.wikipedia.org/wiki/Barnabas) as an apostle:

> But after the apostles, Barnabas and Paul, heard it, they ripped their
garments and dashed into the crowd, ..."

Barnabas was of course not one of the 12, but was a member of the early church.
He may have been an eyewitness to at least some of Jesus' life and teaching. We
first see him in Acts 4:36-37 (MLV):

> Now Joses, who was surnamed Barnabas from the apostles (which is, being
translated, Son of Encouragement), a Levite from Cyprus by birth, sold a field,
possessed by him, and brought the money and placed it beside the apostles’
feet.

See the @lampe1961patristic_lexicon lexicon entry for  αποστολος (emissary,
apostle) (pp. 211 - 214).  It lists five broad categories, of which I is "in
gen", II is "of Christ as sent forth from the Father", and III is "of one sent
by God or Christ to preach and act on his behalf;".  Sub-meaning B of III is
"of NT apostles, comprising 1. The Twelve, ... 2. other leaders of primitive
Church ...", with various entries therein.

From Lampe we see that [Clement of
Alexandria](https://en.wikipedia.org/wiki/Clement_of_Alexandria), writing soon
after AH, refers to [Clement of
Rome](https://en.wikipedia.org/wiki/Clement_of_Rome) (died around 100) as "the
apostle Clement" (Stromata 4, XVII:105) [@anf02,  p. 428].

In the early fourth century, [Eusebius' Ecclesiastical History
(EH)](https://en.wikipedia.org/wiki/Ecclesiastical_History_%28Eusebius%29),
shows a wide view of the term "apostle". From @mcgiffert1890eusebius:

> Afterwards he says he appeared unto James, who was one of the so-called
brethren of the Savior. But, since in addition to these, there were many others
who were called apostles, in imitation of the Twelve, as was Paul himself, he
adds: “Afterward he appeared to all the apostles.” [[1 Corinthians 15:7]] EH 1,
XII:4 [Another version at
BKV](https://bkv.unifr.ch/en/works/cpg-3495/versions/the-church-history-of-eusebius/divisions/14)

## References
